"""init

Revision ID: 5d26287dfe95
Revises: 
Create Date: 2026-08-08 10:41:39.848820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d26287dfe95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_course_id_fkey'), 'attendance', type_='foreignkey')
    op.drop_constraint(op.f('attendance_student_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('courses', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("'card'::character varying"))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("'paid'::character varying"))
    op.drop_constraint(op.f('payments_student_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_course_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_course_student_id_fkey'), 'student_course', type_='foreignkey')
    op.drop_constraint(op.f('student_course_course_id_fkey'), 'student_course', type_='foreignkey')
    op.create_foreign_key(None, 'student_course', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_course', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'last_payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'last_payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.create_foreign_key(op.f('student_course_course_id_fkey'), 'student_course', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('student_course_student_id_fkey'), 'student_course', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_course_id_fkey'), 'payments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('payments_student_id_fkey'), 'payments', 'students', ['student_id'], ['id'])
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'paid'::character varying"))
    op.alter_column('payments', 'method',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'card'::character varying"))
    op.alter_column('courses', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('courses', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_student_id_fkey'), 'attendance', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('attendance_course_id_fkey'), 'attendance', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
